### ISSUE TITLE
TASK - Implement enemy movement patterns

### ISSUE THREAD

**Issue by mfreidel** [FreeDelete-Software/learn2shmup#10]
When enemies spawn in, they should move around the screen a little bit and then move away.

### Pre-flight Checklist

> Verify **all** before submitting

- [x] I have performed *and documented* some basic research and planning before opening this task.
- [x] This task implements a new core feature, or substantially alters an existing one.
- [x] I have confirmed that this is not a duplicate task.
- [x] I have confirmed that this task is not already being worked on or completed.
- [ ] This issue has an assignee.
- [x] This issue is assigned to the **learn2shmup** project.
- [x] This issue is assigned to the appropriate milestone in GitHub.
- [x] This issue has appropriate labels to identify components this may alter.
- [x] I have read, selected, **and verified** the above checkmarks accurately.

### Sub-tasks

Smaller individual tasks required for completion:

- [ ] Implement feature
- [ ] Write documentation and/or notes
- [ ] Manual testing

### Planned procedure

Chronological list of planned work:

1. Create Enemy/path0.tscn to serve as a generic reusable path.
2. Add path0.tscn to the enemy spawning process.
3. After traversing the path, make enemy exit the screen to de-spawn.

### Task research, planning and notes

The easiest method seems to be using the `Path2D` node. This allows you to draw a path which can be followed using the `PathFollow2D` node.

#### Links

1. [API Reference page for Path2D](https://docs.godotengine.org/en/stable/classes/class_path2d.html)
2. [More info about paths and curves](https://docs.godotengine.org/en/stable/tutorials/math/beziers_and_curves.html)
3. [Very short video showing how it is used](https://www.youtube.com/watch?v=C-wLXJ-21KE)
