### ISSUE TITLE
TASK - Set up unit testing with GUT 

### ISSUE THREAD

**Issue by mfreidel** [FreeDelete-Software/learn2shmup#12]
Among other benefits, unit testing provides a fast and consistent means to ensure that new changes haven't broken anything known to be important. While Godot does not provide a built-in framework for unit tests, there is an editor add-on called GUT (Godot Unit Test) which provides this. Significant research is needed on how exactly GUT works and how to integrate it into the project.

### Pre-flight Checklist

> Verify **all** before submitting

- [x] I have performed *and documented* some basic research and planning before opening this task.
- [x] This task implements a new core feature, or substantially alters an existing one.
- [x] I have confirmed that this is not a duplicate task.
- [x] I have confirmed that this task is not already being worked on or completed.
- [x] This issue has an assignee.
- [x] This issue is assigned to the **learn2shmup** project.
- [x] This issue is assigned to the appropriate milestone in GitHub.
- [x] This issue has appropriate labels to identify components this may alter.
- [x] I have read, selected, **and verified** the above checkmarks accurately.

### Sub-tasks

Smaller individual tasks required for completion:

- [x] Configure add-on
- [x] Write some initial tests
- [x] Write documentation and/or notes

### Planned procedure

Chronological list of planned work:

1. RTFM
2. Install add-on
3. Write some simple tests for existing code
4. Add documentation and notes to test/unit/README.md

#### Links

1. https://github.com/bitwes/Gut
2. https://github.com/bitwes/Gut/wiki/Creating-Tests
3. https://github.com/bitwes/Gut/wiki/Asserts-and-Methods
4. video tutorial: https://www.youtube.com/playlist?list=PL6HJEA1Q_FiY1rWcBIMrHrB2F3Xw7Xlcr
5. Working branch: https://github.com/mfreidel/learn2shmup/tree/impl-unit-tests

**Comment by mfreidel** [comment]
Just watching a little of the video tutorial gave me a lot of ideas for improvements to the overall structure and implementation decisions of the existing code. One thing that would be especially useful would be using standard accessors (`get_*` and `set_*` functions). I'll make notes of things like this I notice in the tutorial and do some research into various best practices for Godot. A possible way to handle this sort of improvement is to have a "refactoring" sub-task when merging devel into main for the first stable release (0.1.x --> 0.2.0). This could also be a recurring task for every stable release.

**Comment by mfreidel** [comment]
Pull request has been merged. Documentation exists in: **test/unit/README.md**
