### ISSUE TITLE
TASK - Implement custom addon

### ISSUE THREAD

**Issue by mfreidel** [FreeDelete-Software/learn2shmup#16]
This allows the project to have several "basetype" Nodes with special functions that work together to form a sort of "shmup framework." Using these Nodes will allow a developer to create customized resources that can automatically tie into the game. 

> **NOTE:**
> This task will include changes to naming conventions and the file/folder structure.

### Pre-flight Checklist

> Verify **all** before submitting

- [X] I have performed *and documented* some basic research and planning before opening this task.
- [X] This task implements a new core feature, or substantially alters an existing one.
- [X] I have confirmed that this is not a duplicate task.
- [X] I have confirmed that this task is not already being worked on or completed.
- [X] This issue has an assignee.
- [X] This issue is assigned to the **learn2shmup** project.
- [X] This issue is assigned to the appropriate milestone in GitHub.
- [X] This issue has appropriate labels to identify components this may alter.
- [X] I have read, selected, **and verified** the above checkmarks accurately.

### Sub-tasks

Smaller individual tasks required for completion:

- [x] Create addon with first component 
  - [x] ShmupSpawner
- [x] Convert existing resources
  - [x] Utilize addon
  - [x] New naming conventions
- [x] Write documentation and/or notes
- [x] Manual testing

### Planned procedure

Chronological list of planned work:

1. Create necessary folders and files for the custom addon **with the new naming conventions**
2. Add custom Nodes following the video tutorial in notes.
3. **Do not** implement the game flow changes for ShmupStage.
4. Convert the existing game resources
5. Finalize initial documentation

### Task research, planning and notes

> Pre-flight notes are with code in `docs/notes/custom-addon.md` and `.../naming-conventions.md`

**Comment by mfreidel** [comment]
**NOTE:** The initial scope of this task was reduced to a very simple change. See the linked PR for more details.
