### ISSUE TITLE
TASK - Update "Player" component for new addon system

### ISSUE THREAD

**Issue by mfreidel** [FreeDelete-Software/learn2shmup#18]
> **NOTE:** This task needs more research

The current scene and script files for the player component need to be significantly altered to tie into the new ShmupWorks addon.

Additionally, the shooting functionality should be changed to occur totally inside of the **Player** scene as a part of this change. Doing so should utilize ShmupSpawner in some fashion. Perhaps by adding a **PlayerWeapon** child scene?

### Pre-flight Checklist

> Verify **all** before starting work

- [ ] I have performed *and documented* some basic research and planning before opening this task.
- [X] This task implements a new core feature, or substantially alters an existing one.
- [X] I have confirmed that this is not a duplicate task.
- [X] I have confirmed that this task is not already being worked on or completed.
- [ ] This issue has an assignee.
- [X] This issue is assigned to the **learn2shmup** project.
- [X] This issue is assigned to the appropriate milestone in GitHub.
- [X] This issue has appropriate labels to identify components this may alter.
- [ ] I have read, selected, **and verified** the above checkmarks accurately.

### Sub-tasks

Smaller individual tasks required for completion:

- [ ] Implement feature(s)
  - [ ] Any smaller components?
- [ ] Any extra steps?
- [ ] Write documentation and/or notes
- [ ] Manual testing

### Planned procedure

Chronological list of planned work:

1. Step One
2. Step Two

### Task research, planning and notes

If your pre-flight research/planning notes are not with your code, then paste
them over the contents of this section.
If they *are* with your code, then delete this text except for the following line:

> Pre-flight notes are with code
