### ISSUE TITLE
TASK - Create a simple attack pattern for basic enemy

### ISSUE THREAD

**Issue by mfreidel** [FreeDelete-Software/learn2shmup#5]
> **NOTE:** The art being used for the enemy implies that it fires two projectiles.

The first enemy we made does not attack. It needs a simple pattern to fire bullets while it is moving. Something like firing once every second should be adequate. 

### Pre-flight Checklist

> Verify **all** before submitting

- [X] I have performed *and documented* some basic research and planning before opening this task.
- [X] This task implements a new core feature, or substantially alters an existing one.
- [X] I have confirmed that this is not a duplicate task.
- [X] I have confirmed that this task is not already being worked on or completed.
- [ ] This issue has an assignee.
- [X] This issue is assigned to the **learn2shmup** project.
- [X] This issue is assigned to the appropriate milestone in GitHub.
- [X] This issue has appropriate labels to identify components this may alter.
- [X] I have read, selected, **and verified** the above checkmarks accurately.

### Sub-tasks

Smaller individual tasks required for completion:

- [ ] Implement feature
- [ ] Write documentation and/or notes
- [ ] Manual testing

### Planned procedure

Chronological list of planned work:

> Ensure to connect all signals via script

1. Copy bullet coding from player
2. Modify to shoot moving left (-x)
3. Modify to shoot from two positions (based on the game art)
5. Define shooting pattern using timers based on examples in the documented link (1)

## Links

1. [Godot Docs for connecting signals via code](https://docs.godotengine.org/en/stable/getting_started/step_by_step/signals.html#connecting-a-signal-via-code)
