### ISSUE TITLE
TASK - Implement a system for random enemy spawning

### ISSUE THREAD

**Issue by mfreidel** [FreeDelete-Software/learn2shmup#6]
The game needs a system to continuously spawn in enemies with some randomness.

### Pre-flight Checklist

> Verify **all** before submitting

- [x] I have performed *and documented* some basic research and planning before starting this task.
- [x] This task implements a new core feature, or substantially alters an existing one.
- [x] I have confirmed that this is not a duplicate task.
- [x] I have confirmed that this task is not already being worked on or completed.
- [x] This issue has an assignee.
- [x] This issue is assigned to the **learn2shmup** project.
- [x] This issue is assigned to the appropriate milestone in GitHub.
- [x] This issue has appropriate labels to identify components this may alter.
- [x] I have read, selected, **and verified** the above checkmarks accurately.

### Sub-tasks

Smaller individual tasks required for completion:

- [x] Code
- [x] Documentation
- [x] Testing

### Planned procedure

Chronological list of planned work:

1. Create Enemy/spawner.tscn based on the concepts in the youtube vid (link 1)
2. Add spawning system in level0.tscn and/or level0.gd

### Task research, planning and notes

This should be implemented in a way that can "construct" an enemy into a scene. This would decouple the enemy instancing from the level coding.

#### Links

1. Implementing a "spawning system" in Godot: https://www.youtube.com/watch?v=t24gdhWM3Wo
2. https://docs.godotengine.org/en/stable/getting_started/first_2d_game/05.the_main_game_scene.html

**Comment by mfreidel** [comment]
This was implemented with PR #14
