### ISSUE TITLE
TASK - Implement Player Properties

### ISSUE THREAD

**Issue by mfreidel** [FreeDelete-Software/learn2shmup#7]
> This will probably be a fairly large task and may need to be broken up into smaller pieces before converting into a tracked issue. 

Implementing basic player properties is mainly defining a proper health and damage system. Code should consider the ability to add additional properties in the future.

**Planned Milestone:** 0.3.x

### Pre-flight Checklist

> Verify **all** before submitting

- [ ] I have performed *and documented* some basic research and planning before opening this task.
- [ ] This task implements a new core feature, or substantially alters an existing one.
- [ ] I have confirmed that this is not a duplicate task.
- [ ] I have confirmed that this task is not already being worked on or completed.
- [ ] This issue has an assignee.
- [ ] This issue is assigned to the **learn2shmup** project.
- [ ] This issue is assigned to the appropriate milestone in GitHub.
- [ ] This issue has appropriate labels to identify components this may alter.
- [ ] I have read, selected, **and verified** the above checkmarks accurately.

### Sub-tasks

Smaller individual tasks required for completion:

- [ ] Implement feature(s)
  - [ ] Any smaller components?
- [ ] Any extra steps?
- [ ] Write documentation and/or notes
- [ ] Manual testing

### Planned procedure

Chronological list of planned work:

1. Step One
2. Step Two

### Task research, planning and notes

If your pre-flight research/planning notes are not with your code, then paste
them over the contents of this section.
If they *are* with your code, then delete this text except for the following line:

> Pre-flight notes are with code
